name: mocktail
description: A Dart mock library which simplifies mocking with null safety support and no manual mocks or code generation.
version: 0.4.0
repository: https://github.com/felangel/mocktail
homepage: https://github.com/felangel/mocktail/tree/main/packages/mocktail

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  matcher: ^0.12.10
  test: ^1.21.4

dev_dependencies:
  meta: ^1.3.0
